---
  - name: Playbook to setup mailcow
    hosts: 
      - localhost
    become: true
    tasks:
      # Test Setup without external proxy
      - include_role:
          name: mailcow
        vars:
          MAILCOW_INSTALL_DIR: 'mailcow'
          MAILCOW_HOSTNAME: 'mailcow.example.com'
          MAILCOW_SKIP_LETS_ENCRYPT: 'y'
          MAILCOW_DBPASS: 'secretdbpass'
          MAILCOW_DBROOT: 'secretdbrootpass'
          MAILCOW_BACKUP_LOCATION: '/backup/mailcow'
          MAILCOW_MAILDIR_SUB: ''
          MAILCOW_SKIP_LETS_ENCRYPT: 'n'
